import Head from "next/head";

export default function Coffees() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Coffees</h1>
      </main>
    </div>
  );
}
