import Head from "next/head";

export default function MyConfessions() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My Confessions</h1>
      </main>
    </div>
  );
}
