import Head from "next/head";
import { useQuery, gql } from "@apollo/client";
import { Grid, GridItem } from "@chakra-ui/react";

import ConfessionCard from "../components/ConfessionCard";

const GET_CONFESSIONS = gql`
  query confessions(
    $first: Int
    $skip: Int
    $orderBy: String
    $orderDirection: String
    $where: Confession_filter
  ) {
    confessions(
      first: $first
      skip: $skip
      orderBy: $orderBy
      orderDirection: $orderDirection
      where: $where
    ) {
      id
      hash
      message
      category
      timestamp
      author
    }
  }
`;

export default function Home() {
  const { loading, error, data } = useQuery(GET_CONFESSIONS, {
    variables: {
      first: 10,
      skip: 0,
      orderBy: "timestamp",
      orderDirection: "desc",
    },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error :(</p>;

  console.log(data);
  return (
    <div>
      <Head>
        <title>Confesster Udemy Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid mt="10" templateColumns="repeat(2, 1fr)" gap={6}>
          {data.confessions.map((confession, index) => (
            <GridItem colSpan={1} key={index}>
              <ConfessionCard
                key={index}
                index={index}
                confession={confession}
              />
            </GridItem>
          ))}
        </Grid>
      </main>
    </div>
  );
}
